#!/usr/bin/env bash

set -eu -o pipefail


if [[ $# -ne 3 ]]; then
  echo "USAGE: $0 hostname hosts host.pub|HOST"
  echo "example: $0 host host.i,host.r,host.dse.in.tum.de HOST"
  exit 1
fi

host=$1
hostnames=$2
ip=$3

hosts=$1,$2

dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
workdir=$(mktemp -d)
trap "{ rm -rf "$workdir"; }" EXIT

(
  umask 077
  sops --extract '["ssh-ca"]' -d "$dir/ca-keys.yml" > "$workdir/ssh-ca"
)

cd $workdir
pubkey="${ip}.pub"
cat /home/patrick/key/etc/ssh/ssh_host_ed25519_key.pub > "$pubkey"

ssh-keygen -h -s "$workdir/ssh-ca" -n "$hosts" -I "$(basename "$pubkey" .pub)" "$pubkey"
mv "${ip}-cert.pub" "${dir}/certs/$(echo "$hosts" | grep -o '^[^,]\+')-cert.pub"
