# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ modulesPath
, lib
, config
, ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  nix.nrBuildUsers = 128;

  boot.initrd.availableKernelModules = [ "megaraid_sas" "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems = { 
    "/" = lib.optionalAttrs (config.networking.hostName != "ryan") {
      device = "zroot/root/nixos";
      fsType = "zfs";
    };

    "/boot" = lib.optionalAttrs (config.networking.hostName != "ryan") {
      # set with: dosfslabel /dev/nvme0n1p1 boot
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };
  } // lib.optionalAttrs (config.networking.hostName != "ryan") {
    # we may not have a tmp mountpoint - but then we must not even create a null value for the "/tmp" attribute (which we do for / and /boot)
    "/tmp" = {
      device = "zroot/root/tmp";
      fsType = "zfs";
    };
  };
}
